name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
 build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          env: ${{ secrets.GITHUB_TOKEN }}
      # Snake Animation
      - uses: Platane/snk@master
  with:
    # github user name to read the contribution graph from (**required**)
    # using action context var `github.repository_owner` or specified user
    github_user_name: caroolt
    # path of the generated svg file
    # If left empty, the svg file will not be generated
    svg_out_path: dist/github-user-contribution.svg

   - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}